FORECAST_FORECASTIO_API_KEY = 'loremipsum'
FORECAST_COORDINATES = [50.123, 12.456]
FORECAST_UNITS = 'si'
FORECAST_CACHE_FILE = '/tmp/weatherpod.pkl'
FORECAST_CACHE_LIFETIME = 120

RENDERER_ICONS_PATH = 'icons'
RENDERER_FONT = 'fonts/Roboto-Regular.ttf'
RENDERER_RANDOM_PIC_PROVIDER_URL = 'http://lorempixel.com/g/400/300/'
